import { useState } from "react";
import toast from "react-hot-toast";
import Button from "../Button.jsx";

const RECOVERY_CODES = [
  "ABCD-1234-EFGH", "IJKL-5678-MNOP",
  "QRST-9012-UVWX", "YZAB-3456-CDEF",
  "GHIJ-7890-KLMN", "OPQR-1234-STUV"
];

export default function TwoFactorTab() {
  const [enabled, setEnabled] = useState(false);
  const [setupStep, setSetupStep] = useState(0); // 0 = standard, 1 = QR code, 2 = recovery codes
  const [code, setCode] = useState("");

  function handleEnable() {
    setSetupStep(1);
  }

  function handleVerifyCode(e) {
    e.preventDefault();
    if (code.length === 6 && /^\d+$/.test(code)) {
      setSetupStep(2);
      toast.success("2FA code verified!");
    } else {
      toast.error("Please enter a valid 6-digit verification code");
    }
  }

  function handleCompleteSetup() {
    setEnabled(true);
    setSetupStep(0);
    setCode("");
    toast.success("Two-Factor Authentication is now enabled!");
  }

  function handleDisable() {
    if (confirm("Are you sure you want to disable 2FA? This will decrease your account security.")) {
      setEnabled(false);
      setSetupStep(0);
      setCode("");
      toast.success("Two-Factor Authentication has been disabled.");
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-slate-950 dark:text-white">Two-Factor Authentication (2FA)</h2>
        <p className="text-sm text-slate-500 dark:text-slate-400">Add an extra layer of security to your account by requiring a verification code during login.</p>
      </div>

      <div className="max-w-xl p-5 border border-slate-200 dark:border-slate-800 rounded-xl bg-white dark:bg-slate-900 shadow-sm">
        {/* Status Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-100 dark:border-slate-800">
          <div>
            <h3 className="font-semibold text-slate-800 dark:text-slate-200">2FA Status</h3>
            <p className="text-xs text-slate-500 mt-0.5">
              {enabled ? "Your account is secured with two-factor authentication." : "Two-factor authentication is currently disabled."}
            </p>
          </div>
          <span className={`px-2.5 py-1 rounded-full text-xs font-bold ${enabled ? "bg-green-100 text-green-700 dark:bg-green-950/30 dark:text-green-400" : "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-400"}`}>
            {enabled ? "Enabled" : "Disabled"}
          </span>
        </div>

        {/* Dynamic setup states */}
        {setupStep === 0 && (
          <div className="pt-4 space-y-4">
            <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
              When enabled, you will be prompted for a 6-digit security code generated by your mobile authenticator app (like Google Authenticator, Authy, or 1Password) after entering your password.
            </p>
            {enabled ? (
              <Button onClick={handleDisable} variant="soft" className="border-red-200 text-red-600 dark:border-red-950/30 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-950/20">
                Disable 2FA
              </Button>
            ) : (
              <Button onClick={handleEnable}>
                Set Up 2FA
              </Button>
            )}
          </div>
        )}

        {setupStep === 1 && (
          <form onSubmit={handleVerifyCode} className="pt-4 space-y-4">
            <h4 className="font-semibold text-slate-800 dark:text-slate-200">Step 1: Scan QR Code</h4>
            <p className="text-sm text-slate-500 dark:text-slate-400">Scan this QR code with your authenticator app to sync your account.</p>
            
            {/* Mock QR Code */}
            <div className="flex justify-center p-4 bg-slate-100 dark:bg-slate-800 rounded-lg w-48 h-48 mx-auto items-center">
              <svg className="w-40 h-40 text-slate-900 dark:text-white" viewBox="0 0 24 24" fill="currentColor">
                <path d="M3 3h8v8H3zm2 2v4h4V5zm12-2h4v4h-4zm0 6h4v2h-4zm-6 2h2v4h-2zm8 2h2v4h-2zm-6 2h4v2h-4zm2 2h4v2h-4zM3 13h8v8H3zm2 2v4h4v-4zm8-12h4v8h-4zm2 2v4h0z"/>
              </svg>
            </div>
            
            <p className="text-xs text-slate-400 text-center">Can't scan? Enter key: <code className="bg-slate-100 px-1 py-0.5 rounded text-slate-800 dark:bg-slate-800 dark:text-slate-300 font-mono">CONVILARGE2FAKEY2026</code></p>

            <div className="space-y-2 pt-2">
              <label className="block text-sm font-semibold">
                Verification Code
                <input
                  type="text"
                  placeholder="000000"
                  maxLength={6}
                  className="focus-ring mt-2 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950 text-slate-900 dark:text-white text-center font-mono tracking-widest"
                  value={code}
                  onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
                />
              </label>
            </div>

            <div className="flex gap-2 justify-end pt-2">
              <button type="button" onClick={() => setSetupStep(0)} className="px-4 py-2 text-sm font-bold text-slate-500 hover:bg-slate-100 rounded-lg dark:hover:bg-slate-800">Cancel</button>
              <Button type="submit">Verify Code</Button>
            </div>
          </form>
        )}

        {setupStep === 2 && (
          <div className="pt-4 space-y-4">
            <h4 className="font-semibold text-slate-800 dark:text-slate-200">Step 2: Recovery Codes</h4>
            <p className="text-sm text-slate-500 dark:text-slate-400">Save these backup codes in a safe place. You can use them to access your account if you lose your phone.</p>
            
            <div className="grid grid-cols-2 gap-2 p-3 bg-slate-50 dark:bg-slate-950 rounded-lg font-mono text-xs text-slate-700 dark:text-slate-300 border border-slate-150 dark:border-slate-800">
              {RECOVERY_CODES.map((c) => (
                <div key={c} className="text-center py-1">{c}</div>
              ))}
            </div>

            <div className="flex gap-2 justify-end pt-2">
              <Button onClick={handleCompleteSetup}>Finish Setup</Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
